# Generated by Django 5.2.1 on 2025-07-09 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('leszek_app', '0001_initial'), ('leszek_app', '0002_alter_question_correct_answer_alter_question_media'), ('leszek_app', '0003_rename_text_question_question'), ('leszek_app', '0004_rename_asnwer_b_question_answer_b'), ('leszek_app', '0005_alter_questionapplication_user_id_and_more'), ('leszek_app', '0006_remove_questionapplication_questionid_and_more'), ('leszek_app', '0007_question_questionapplication'), ('leszek_app', '0008_alter_question_id'), ('leszek_app', '0009_rename_questionid_questionapplication_question_id_and_more'), ('leszek_app', '0010_alter_question_unique_together'), ('leszek_app', '0011_alter_questionapplication_question_id_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=10000)),
                ('answer_a', models.CharField(max_length=5000)),
                ('answer_b', models.CharField(max_length=5000)),
                ('answer_c', models.CharField(max_length=5000)),
                ('answer_d', models.CharField(max_length=5000)),
                ('correct_answer', models.CharField(blank=True, max_length=5000, null=True)),
                ('media', models.CharField(blank=True, max_length=5000, null=True)),
                ('code_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leszek_app.code')),
            ],
            options={
                'unique_together': {('question', 'answer_a', 'answer_b', 'answer_c', 'answer_d', 'code_id')},
            },
        ),
        migrations.CreateModel(
            name='QuestionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(max_length=5000)),
                ('sent_at', models.DateTimeField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leszek_app.question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
