# Generated by Django 5.1.6 on 2025-03-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leszek_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='media',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
