# Generated by Django 5.1.6 on 2025-03-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leszek_app', '0003_rename_text_question_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='asnwer_b',
            new_name='answer_b',
        ),
    ]
