# Generated by Django 5.1.6 on 2025-03-19 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leszek_app', '0004_rename_asnwer_b_question_answer_b'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionapplication',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question', 'media', 'code_id')},
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
