# Generated by Django 5.1.6 on 2025-03-19 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leszek_app', '0005_alter_questionapplication_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionapplication',
            name='questionID',
        ),
        migrations.RemoveField(
            model_name='questionapplication',
            name='user_ID',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionApplication',
        ),
    ]
