# Generated by Django 5.1.6 on 2025-03-19 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leszek_app', '0006_remove_questionapplication_questionid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10000)),
                ('answer_a', models.CharField(max_length=5000)),
                ('answer_b', models.CharField(max_length=5000)),
                ('answer_c', models.CharField(max_length=5000)),
                ('answer_d', models.CharField(max_length=5000)),
                ('correct_answer', models.CharField(blank=True, max_length=5000, null=True)),
                ('media', models.CharField(blank=True, max_length=5000, null=True)),
                ('code_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leszek_app.code')),
            ],
            options={
                'unique_together': {('question', 'media', 'code_id')},
            },
        ),
        migrations.CreateModel(
            name='QuestionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(max_length=5000)),
                ('sent_at', models.DateTimeField()),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leszek_app.question')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
