# Generated by Django 5.2.1 on 2025-05-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leszek_app', '0008_alter_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionapplication',
            old_name='questionID',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='questionapplication',
            old_name='user_ID',
            new_name='user_id',
        ),
    ]
