# Generated by Django 5.2.1 on 2025-06-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leszek_app', '0009_rename_questionid_questionapplication_question_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question', 'answer_a', 'answer_b', 'answer_c', 'answer_d', 'code_id')},
        ),
    ]
